server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:trdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  tracing:
    enabled: true

  application:
    name: tr-service
  opentelemetry:
    tracing:
      enabled: true
      exporter:
        otlp:
          endpoint: http://localhost:4320 # Grafana Tempo가 수신하는 OpenTelemetry 포트
