version: "3.7"
services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "4321:4321" # OpenTelemetry 수집용 gRPC 포트
      - "3100:3100" # Grafana Tempo HTTP API
    volumes:
      - ./tempo-data:/var/lib/tempo
      - ./tempo.yaml:/etc/tempo/tempo.yaml
    command: ["-config.file=/etc/tempo/tempo.yaml"]
